### ISSUE TITLE
Size of number in Booth's Multiplication

### ISSUE THREAD

**Issue by murtraja** [akanimax/CL-3_lab_2017#1] opened 2017-02-09 01:14 UTC
The fact that we can multiply only numbers in the range 0 to 2^limit is a bit constrained.
i propose that we should take any two numbers and then equalize the bits before calling multiply (a call like equalize_bits(num1, num2) )
if we can achieve this, then the check that bits must be a multiple of 4 can be avoided easily

P.S. check out [bit_length()](https://docs.python.org/3/library/stdtypes.html#int.bit_length) function

**Comment by akanimax** [comment] 2017-02-09 05:49
Agreed! When I looked at this task, I thought it would be okay to make it a bit restricted and the equalize_bits() functionality might be implemented by the user of the API. But, you are right. This API should be as simple to use as possible. 

I have changed the original implementation making the code even more clean and easy to understand. 

Now, any two numbers can be multiplied irrespective of the size. Hope, the issue is resolved.
This issue is a bit tricky, so, I'll leave this one to you @murtraja to close it if you are satisfied with the new implementation.

**Comment by murtraja** [comment] 2017-02-11 18:00
![booths-algorithm](https://cloud.githubusercontent.com/assets/7806954/22856156/05868392-f0b2-11e6-80bf-886c986d7918.jpg)

**Comment by murtraja** [comment] 2017-02-11 18:01
i was thinking along these lines. I was unable to understand the algorithm from the video. i read the comments, some of them mentioned that the algorithm is wrong. not sure. i want to stick with this one. And since you study from reference books, this image will ring some bells for you!

**Comment by akanimax** [comment] 2017-02-11 18:03
This is the same same algorithm that I used. Exactly same in fact. All I have done is added a sign bit to the number for making it a signed integer.

**Closed as completed** 2017-07-01 03:38 UTC
